import * as cheerio from 'cheerio';
import {money} from './engine.js';
const paths=['agentplayerlist.php','history_trans.php','tl_summaryagent.php','masteruserdetil.php','editcoinhis.php','admin_transaksi.php'];
export function safeBase(s){const u=new URL(s);if(u.protocol!=='https:'||u.username||u.password||u.search||u.hash)throw Error('Agent base must be HTTPS');return u.origin;}
export class Agent{constructor(base,cookie){this.base=safeBase(base);if(!cookie||/[\r\n]/.test(cookie))throw Error('Cookie sesi tidak valid');this.cookie=cookie;}
 async load(page,{method='GET',form={},query={}}={}){if(!paths.includes(page))throw Error('Path tidak diizinkan');let url=new URL('/'+page,this.base);for(const [k,v] of Object.entries(query))url.searchParams.set(k,String(v));const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),15000);try{const r=await fetch(url,{method,headers:{Cookie:this.cookie,'Content-Type':'application/x-www-form-urlencoded','User-Agent':'OMTOGEL-AUDIT/1.0'},body:method==='POST'?new URLSearchParams(form):undefined,redirect:'manual',signal:controller.signal});if(r.status>=300&&r.status<400)throw Error('Sesi tidak aktif (redirect)');if(!r.ok)throw Error('Panel HTTP '+r.status);let html=await r.text();if(html.length>5_000_000)throw Error('Halaman terlalu besar');if(/type=["']password["']|name=["'](?:password|passwd)["']/i.test(html))throw Error('Sesi tidak valid: panel meminta login');return html;}finally{clearTimeout(timer);}}
}
export function parseProfile(html,id){const $=cheerio.load(html);const tr=$('tr').filter((_,el)=>$(el).text().toLowerCase().includes(id.toLowerCase())).first();if(!tr.length)return null;const t=tr.find('td').map((_,e)=>$(e).text().trim()).get();return {user:id,balance:money(t[4]),joined:t[5]||null};}
export function parseCoin(html){const $=cheerio.load(html);const rows=[];$('tr').each((_,el)=>{const cells=$(el).find('td').map((_,e)=>$(e).text().trim()).get();if(cells.length===6&&/^\d+$/.test(cells[0])&&/^\d{2}-\d{2}-\d{4}/.test(cells[1]))rows.push({date:cells[1],info:cells[2],by:cells[3],amount:money(cells[4]),lastCoin:money(cells[5])});});return rows;}
export function parseSummary(html){const $=cheerio.load(html);const data=[];$('tr').each((_,e)=>{const c=$(e).find('td').map((_,n)=>$(n).text().replace(/\s+/g,' ').trim()).get();if(c.length>=4&&c[0]&&/^(slot|toto|live game|pragmatic play|total all|poker|arcade|elottery|saba sportsbook|sbo sportsbook)$/i.test(c[0]))data.push({game:c[0],to:money(c[1]),result:money(c[3])});});return data;}
export function parseHistory(html){const $=cheerio.load(html);const rows=[];$('tr').each((_,el)=>{const c=$(el).find('td').map((_,e)=>$(e).text().replace(/\s+/g,' ').trim()).get();if(c.length<7||!/^(?:\d{1,3})$/.test(c[0]))return;const status=c.findIndex(x=>/^menang$/i.test(x));if(status<0)return;const detail=c.find(x=>/menang /i.test(x))||'Menang (game tidak teridentifikasi)';const game=detail.replace(/^menang\s*/i,'').trim()||'Tidak diketahui';const creditIndex=status+2;const amount=creditIndex<c.length?money(c[creditIndex]):null;rows.push({game,amount:Number.isFinite(amount)?amount:null,date:c.find(x=>/^\d{4}-\d{2}-\d{2}/.test(x))||null});});return rows;}
export async function auditMember(agent,user,from,to){const warnings=[];let profile=null,coins=[],summary=[],wins=[];const run=async(label,fn)=>{try{return await fn()}catch(e){warnings.push(`${label}: ${e.message}`);return null}};
 const p=await run('Profil',async()=>parseProfile(await agent.load('agentplayerlist.php',{method:'POST',form:{user,usercheck:'1',cari:'Cari',page:'1'}}),user));profile=p;
 const c=await run('History coin',async()=>parseCoin(await agent.load('editcoinhis.php',{method:'POST',form:{user,cmdsend:'History Bank'}})));if(c)coins=c;
 const h=await run('Kemenangan',async()=>parseHistory(await agent.load('admin_transaksi.php',{method:'POST',form:{namague:user,submit:'Submit'}})));if(h)wins=h;
 const s=await run('TurnOver',async()=>parseSummary(await agent.load('tl_summaryagent.php',{method:'POST',query:{user:process.env.AGENT_USERNAME||''},form:{valdate1:from,valdate2:to,game:'ALL',viewplayers:'1',addWhere:user,viewPoker:'1',isNotFirst:'1',submit:'Submit',page:'0'}})));if(s)summary=s;
 const depositRow=coins.find(x=>/deposit/i.test(x.info));const withdrawRow=coins.find(x=>/withdraw/i.test(x.info));
 // Summary endpoint is aggregated by game and may show other players. Never use its totals as user-specific validated TO without a verified member-level breakdown.
 if(summary.length)warnings.push('TO ringkasan belum terbukti khusus User ID; perlu validasi detail per member');
 warnings.push('Klaim bonus belum dapat dibuktikan oleh halaman yang tersedia');
 return {user,profile,deposit:depositRow?.amount??null,depositTime:depositRow?.date,withdraw:withdrawRow?.amount??null,wins,bonusKind:null,turnover:null,target:null,remaining:null,status:'PERLU VERIFIKASI',warnings,sources:{coinRows:coins.length,summaryRows:summary.length}};
}
