import * as cheerio from 'cheerio';
import {money,evaluateTO} from './engine.js';
const paths=['agentplayerlist.php','history_trans.php','tl_summaryagent.php','masteruserdetil.php','editcoinhis.php','admin_transaksi.php'];
export function safeBase(s){const u=new URL(s);if(u.protocol!=='https:'||u.username||u.password||u.search||u.hash)throw Error('Agent base must be HTTPS');return u.origin;}
export class Agent{constructor(base,cookie){this.base=safeBase(base);if(!cookie||/[\r\n]/.test(cookie))throw Error('Cookie sesi tidak valid');this.cookie=cookie;}
 async load(page,{method='GET',form={},query={}}={}){if(!paths.includes(page))throw Error('Path tidak diizinkan');const url=new URL('/'+page,this.base);for(const [k,v] of Object.entries(query))url.searchParams.set(k,String(v));const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),20000);try{const r=await fetch(url,{method,headers:{Cookie:this.cookie,'Content-Type':'application/x-www-form-urlencoded','User-Agent':'OMTOGEL-AUDIT/1.0'},body:method==='POST'?new URLSearchParams(form):undefined,redirect:'manual',signal:controller.signal});if(r.status>=300&&r.status<400)throw Error('Sesi tidak aktif (redirect)');if(!r.ok)throw Error('Panel HTTP '+r.status);const html=await r.text();if(html.length>5_000_000)throw Error('Halaman terlalu besar');if(/type=["']password["']|name=["'](?:password|passwd)["']/i.test(html))throw Error('Sesi tidak valid: panel meminta login');return html;}finally{clearTimeout(timer);}}
}
const clean=(s)=>String(s??'').replace(/\s+/g,' ').trim();
export function parseProfile(html,id){const $=cheerio.load(html);const tr=$('tr').filter((_,el)=>$(el).find('td').toArray().some(c=>clean($(c).text()).toLowerCase()===id.toLowerCase())).first();if(!tr.length)return null;const t=tr.find('td').map((_,e)=>clean($(e).text())).get();return {user:id,balance:money(t[4]),joined:t[5]||null};}
export function parseCoin(html){const $=cheerio.load(html);const rows=[];$('tr').each((_,el)=>{const cells=$(el).children('td').map((_,e)=>clean($(e).text())).get();if(cells.length===6&&/^\d+$/.test(cells[0])&&/^\d{2}-\d{2}-\d{4}/.test(cells[1]))rows.push({date:cells[1],info:cells[2],by:cells[3],amount:money(cells[4]),lastCoin:money(cells[5])});});return rows;}
export function parseMemberSummary(html,user){const $=cheerio.load(html);const matches=[];let hasTable=false;$('table.highlightrow').each((_,tbl)=>{$(tbl).find('tr').each((__,el)=>{const cells=$(el).children('td');const txt=cells.map((___,td)=>clean($(td).text())).get();if(txt.some(v=>/^(id pemain|turnover)$/i.test(v)))hasTable=true;if(txt.length<5)return;const link=cells.eq(1).find('a[href*="masteruserdetil.php"]');const id=clean(link.text())||txt[1];if(id.toLowerCase()!==String(user).toLowerCase())return;const values=cells.slice(2).map((___,e)=>clean($(e).text())).get();if(!values.length)return;matches.push({user:id,to:money(values[0]),netResult:money(values[1]),promotion:money(values[2]),link:link.attr('href')||null});});});return {rows:matches,hasTable};}
export function parseHistoryRows(html){const $=cheerio.load(html);const rows=[];$('tr').each((_,el)=>{const c=$(el).children('td').map((__,n)=>clean($(n).text())).get();if(c.length!==9||!/^\d+$/.test(c[0])||!/^\d{4}-\d{2}-\d{2}/.test(c[2]))return;rows.push({date:c[2],description:c[3],status:c[4],debit:money(c[5]),credit:money(c[6]),game:clean(c[3].replace(/^(?:menang|beli)\s+/i,'')),type:/^menang$/i.test(c[4])?'WIN':/^beli$/i.test(c[4])?'BET':'OTHER'});});const next=$('a[href*="admin_transaksi.php"]').toArray().map(el=>$(el).attr('href')).find(href=>/\bstart=\d+/.test(href||''));return {rows,next:next||null};}
export function parseHistory(html){return parseHistoryRows(html).rows.filter(x=>x.type==='WIN').map(x=>({game:x.game,amount:x.credit,date:x.date}));}
function parseStamp(s){const m=String(s||'').match(/^(\d{2})-(\d{2})-(\d{4})\s+(\d{2}):(\d{2}):(\d{2})/);if(!m)return null;return Date.UTC(+m[3],+m[2]-1,+m[1],+m[4],+m[5],+m[6]);}
function detectBonus(coins){const sorted=[...coins].filter(r=>parseStamp(r.date)!==null).sort((a,b)=>parseStamp(a.date)-parseStamp(b.date));const deposits=sorted.filter(r=>/^deposit(?:\s*\(PGA\))?$/i.test(r.info)&&r.amount>0);const candidates=sorted.filter(r=>/deposit/i.test(r.info)&&r.amount>0&&(/manual|bonus/i.test(r.info)||(/^(?:deposit)$/i.test(r.info)&&r.by&&!/^(?:PGA)$/i.test(r.by))));let result=null;for(const dp of deposits){for(const bonus of candidates){const minutes=(parseStamp(bonus.date)-parseStamp(dp.date))/60000;if(minutes<=0||minutes>60||dp===bonus)continue;const kind=dp.amount>=50000&&bonus.amount===Math.min(dp.amount*.5,500000)?'FREEBET':dp.amount>=100000&&bonus.amount===5000?'DAILY':null;if(!kind)continue;const value={kind,amount:bonus.amount,deposit:dp.amount,depositTime:dp.date,bonusTime:bonus.date,minutes,confidence:'INDIKASI'};if(!result||parseStamp(bonus.date)>parseStamp(result.bonusTime))result=value;}}return {bonus:result,deposit:deposits.at(-1)||null};}
export async function auditMember(agent,user,from,to){const warnings=[];let profile=null,coins=[],wins=[],memberSummary=null,historyRows=[],summaryOk=false,historyComplete=false;const run=async(label,fn)=>{try{return await fn()}catch(e){warnings.push(`${label}: ${e.message}`);return null}};
 profile=await run('Profil',async()=>parseProfile(await agent.load('agentplayerlist.php',{method:'POST',form:{user,usercheck:'1',cari:'Cari',page:'1'}}),user));
 const coinResult=await run('History coin',async()=>parseCoin(await agent.load('editcoinhis.php',{method:'POST',form:{user,cmdsend:'History Bank'}})));if(coinResult)coins=coinResult;
 const history=await run('Kemenangan',async()=>{let page=await agent.load('admin_transaksi.php',{query:{namauser:user,cariuser:'Cari'}});const combined=[];const seen=new Set();let completed=false;for(let p=0;p<8;p++){const result=parseHistoryRows(page);combined.push(...result.rows);if(!result.next){completed=true;break}const url=new URL(result.next,agent.base);if(url.pathname!=='/admin_transaksi.php'||seen.has(url.search))break;seen.add(url.search);page=await agent.load('admin_transaksi.php',{query:Object.fromEntries(url.searchParams)});}return {rows:combined,complete:completed};});if(history){historyRows=history.rows;historyComplete=history.complete;wins=historyRows.filter(r=>r.type==='WIN').map(r=>({game:r.game,amount:r.credit,date:r.date}));}
 const summary=await run('TurnOver',async()=>parseMemberSummary(await agent.load('tl_summaryagent.php',{method:'POST',query:{user:process.env.AGENT_USERNAME||''},form:{valdate1:from,valdate2:to,game:'ALL',viewplayers:'1',addWhere:user,viewPoker:'1',isNotFirst:'1',submit:'Submit',page:'1'}}),user));if(summary){summaryOk=summary.hasTable;memberSummary=summary.rows.length===1?summary.rows[0]:null;}
 if(!profile)warnings.push('Profil member tidak ditemukan');if(!coins.length)warnings.push('History Coin belum terbaca');if(!summaryOk)warnings.push('Tabel laporan TO belum dikenali');else if(!memberSummary)warnings.push('Baris TO untuk ID member belum ditemukan');if(!history)warnings.push('Riwayat kemenangan gagal diambil');else if(!historyComplete)warnings.push('Riwayat kemenangan lebih panjang dari batas pencarian; hasil tidak lengkap');
 const {bonus,deposit}=detectBonus(coins);if(bonus)warnings.push('Pola bonus terdeteksi berdasarkan nominal/waktu; belum ada bukti keterangan bonus resmi');else warnings.push('Tidak ditemukan pola bonus pada history yang terbaca; bukan bukti tidak klaim bonus');
 const turnover=memberSummary?.to??null;const bonusKind=bonus?.kind||null;const targetBase=bonus?.deposit??deposit?.amount??null;const evaluation=targetBase!==null?evaluateTO({deposit:targetBase,bonusKind:bonusKind||'NONE',bonusAmount:bonus?.amount||0,turnover,verified:Boolean(memberSummary&&deposit&&bonus&&bonus.confidence==='VERIFIED')}):null;
 // Daily turnover may include bets before the relevant deposit. It is not automatically eligible turnover.
 return {user,profile,reportDate:from,turnoverPeriod:{from,to},deposit:deposit?.amount??null,depositTime:deposit?.date??null,withdraw:coins.find(r=>/withdraw/i.test(r.info))?.amount??null,wins,bonusKind:bonus?.kind||null,bonusAmount:bonus?.amount??null,bonusConfidence:bonus?.confidence||'BELUM TERVERIFIKASI',turnover,target:evaluation?.target??null,remaining:null,status:'PERLU VERIFIKASI',warnings,sources:{coinRows:coins.length,summaryRows:summary?.rows.length||0,historyRows:historyRows.length,historyComplete}};
}
