import express from 'express';import crypto from 'node:crypto';import {init,db,setting,save,encrypt,logs,audit} from './store.js';import {Agent} from './adapter.js';import {runCheck} from './server-logic.js';import {runBot} from './telegram.js';
// Validasi konfigurasi saat startup: password admin tidak perlu sepanjang kunci enkripsi.
// Minimal 12 karakter untuk password; session secret dan encryption key minimal 32.
const required = {
  DATABASE_URL: 1,
  ADMIN_USERNAME: 1,
  ADMIN_PASSWORD: 12,
  SESSION_SECRET: 32,
  ENCRYPTION_KEY: 32
};
const errors = Object.entries(required).filter(([key, minimum]) =>
  typeof process.env[key] !== 'string' || process.env[key].length < minimum
).map(([key, minimum]) => `${key} (minimal ${minimum} karakter)`);
if (errors.length) {
  console.error('[STARTUP] Konfigurasi Railway belum lengkap: ' + errors.join(', '));
  console.error('[STARTUP] Railway > service aplikasi > Variables; simpan perubahan lalu deploy versi terbaru. Jangan kirim nilai rahasia ke log.');
  process.exit(1);
}

const app=express();app.disable('x-powered-by');app.set('trust proxy',1);app.use(express.urlencoded({extended:false,limit:'8kb'}));app.use(express.json({limit:'8kb'}));app.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','DENY');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('Content-Security-Policy',"default-src 'none'; style-src 'unsafe-inline'; form-action 'self'; base-uri 'none'; frame-ancestors 'none'");next()});
const h=s=>String(s??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const sign=s=>crypto.createHmac('sha256',process.env.SESSION_SECRET).update(s).digest('hex');const valid=(a,b)=>a?.length===b?.length&&crypto.timingSafeEqual(Buffer.from(a),Buffer.from(b));
function auth(req,res,next){const raw=(req.headers.cookie||'').match(/(?:^|;\s*)audit_auth=([^;]+)/)?.[1];if(!raw)return res.redirect('/login');const [exp,sig]=raw.split('.');if(!/^\d+$/.test(exp)||Date.now()>Number(exp)||!valid(sig,sign(exp)))return res.redirect('/login');next()}
function csrf(req){return sign('csrf:'+((req.headers.cookie||'').match(/audit_auth=([^;]+)/)?.[1]||''))}
function html(title,body){return `<!doctype html><html lang="id"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${h(title)}</title><style>body{margin:0;background:#0b1220;color:#e7edf7;font:15px system-ui}main{max-width:1020px;margin:35px auto;padding:20px}header{background:#14243b;padding:18px;border-radius:14px;margin-bottom:20px}a{color:#60c7ff}nav a{margin-right:18px}.card{background:#14243b;padding:22px;border:1px solid #29405b;border-radius:14px;margin:12px 0}label{display:block;margin:13px 0 5px}input,button{padding:12px;border-radius:8px;border:1px solid #455a78;background:#0e192b;color:white;max-width:100%;box-sizing:border-box}input{width:100%}button{background:#008cc2;border:0;cursor:pointer;font-weight:700}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:11px;border-bottom:1px solid #345}pre{white-space:pre-wrap;overflow-wrap:anywhere}.muted{color:#a7bdd4}small{color:#9cb1c8}</style><main><header><h2>🛡️ OMTOGEL AUTO AUDIT</h2><nav><a href="/">Dashboard</a><a href="/settings">Pengaturan</a><a href="/logs">Audit Logs</a><a href="/logout">Logout</a></nav></header>${body}</main></html>`}
app.get('/health',async(req,res)=>{try{await db().query('SELECT 1');res.json({ok:true})}catch{res.status(503).json({ok:false})}});
app.get('/login',(req,res)=>res.send(html('Login',`<section class="card"><h3>Login Admin</h3><form method="post" action="/login"><label>Username</label><input name="user" required><label>Password</label><input name="pass" type="password" required><br><br><button>Masuk</button></form></section>`)));
const attempts=new Map();app.post('/login',(req,res)=>{const ip=req.ip;const t=attempts.get(ip)||{count:0,until:0};if(t.until>Date.now())return res.status(429).send('Terlalu banyak percobaan');const ok=valid(sign(String(req.body.user)),sign(process.env.ADMIN_USERNAME))&&valid(sign(String(req.body.pass)),sign(process.env.ADMIN_PASSWORD));if(!ok){t.count++;if(t.count>=5){t.until=Date.now()+15*60*1000;t.count=0}attempts.set(ip,t);return res.status(401).send('Login gagal. <a href="/login">Coba lagi</a>')}attempts.delete(ip);const exp=String(Date.now()+12*3600*1000);res.cookie('audit_auth',exp+'.'+sign(exp),{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'strict',maxAge:12*3600*1000});res.redirect('/')});
app.get('/logout',(req,res)=>{res.clearCookie('audit_auth');res.redirect('/login')});
app.get('/',auth,async(req,res)=>res.send(html('Dashboard',`<section class="card"><h3>🔍 Pemeriksaan Manual</h3><form action="/check" method="post"><input type="hidden" name="csrf" value="${csrf(req)}"><label>User ID</label><input name="user" required pattern="[a-zA-Z][a-zA-Z0-9_]{2,24}" placeholder="lurin21"><br><br><button>Cek Member</button></form><p class="muted">Bot otomatis memeriksa laporan grup apabila token, Group ID, dan sesi agent sudah disimpan.</p></section>`)));
app.post('/check',auth,verifyCsrf,async(req,res)=>{try{const user=String(req.body.user||'');if(!/^[a-z][a-z0-9_]{2,24}$/i.test(user))throw Error('User ID tidak valid');const result=await runCheck(user);await audit(result.user,'MANUAL',result);res.send(html('Hasil Audit',`<section class="card"><h3>Hasil: ${h(result.user)}</h3><pre>${h(JSON.stringify(result,null,2))}</pre></section>`))}catch(e){res.status(400).send(html('Kesalahan',`<section class="card">${h(e.message)}</section>`))}});
function verifyCsrf(req,res,next){if(!valid(sign(String(req.body.csrf||'')),sign(csrf(req))))return res.status(403).send('CSRF tidak valid');next()}
app.get('/settings',auth,async(req,res)=>{const has=!!await setting('agent_cookie');res.send(html('Pengaturan',`<section class="card"><h3>Agent Session ${has?'✅ Tersimpan':'⚠️ Belum dipasang'}</h3><p class="muted">Tempel Cookie dari sesi milik sendiri yang diizinkan. Jangan memakai cookie akun orang lain. Sesi disimpan dengan AES-256-GCM dan tidak ditampilkan kembali.</p><form action="/settings/session" method="post"><input type="hidden" name="csrf" value="${csrf(req)}"><label>Cookie HTTP sesi agent</label><input name="cookie" type="password" autocomplete="off" required><br><br><button>Simpan dan Uji Session</button></form><form action="/settings/clear" method="post"><input type="hidden" name="csrf" value="${csrf(req)}"><br><button>Cabut Session</button></form></section><section class="card"><h3>Telegram — Grup Disetujui Admin</h3><p class="muted">Hanya admin panel dapat menyimpan Group ID yang diizinkan. Bot mengabaikan grup lainnya. Setelan Telegram untuk siapa yang dapat mengundang bot dikelola oleh admin grup Telegram. Semua anggota grup terdaftar, termasuk non-admin, bisa mengirim laporan dan membaca reply. Matikan Privacy Mode bot lewat BotFather untuk memproses pesan biasa seperti ID: user WD 4 juta.</p><p class="muted">Token bot dan Group ID juga dapat diisi menggunakan Environment Variables Railway.</p><form method="post" action="/settings/telegram"><input type="hidden" name="csrf" value="${csrf(req)}"><label>Bot Token</label><input name="token" type="password" autocomplete="off" required><label>Group ID (contoh -100...)</label><input name="group" required pattern="-?[0-9]+"><br><br><button>Simpan Telegram</button></form></section>`))});
app.post('/settings/session',auth,verifyCsrf,async(req,res)=>{try{const cookie=String(req.body.cookie||'').trim();const agent=new Agent(process.env.AGENT_BASE_URL||'https://agwl5.suksesbogil.com',cookie);await agent.load('agentplayerlist.php');await save('agent_cookie',encrypt(cookie));res.send(html('Session',`<section class="card">✅ Sesi disimpan; koneksi halaman playerlist berhasil. <a href="/settings">Kembali</a><p>Ini belum menjamin akses ke semua halaman.</p></section>`))}catch(e){res.status(400).send(html('Gagal',`<section class="card">Sesi gagal diuji: ${h(e.message)}</section>`))}});
app.post('/settings/clear',auth,verifyCsrf,async(req,res)=>{await db().query('DELETE FROM settings WHERE k=$1',['agent_cookie']);res.redirect('/settings')});
app.post('/settings/telegram',auth,verifyCsrf,async(req,res)=>{if(!/^\d+:[\w-]{25,}$/.test(req.body.token||'')||! /^-?\d+$/.test(req.body.group||''))return res.status(400).send('Token/Group ID invalid');await save('telegram_token',String(req.body.token));await save('telegram_group',String(req.body.group));res.redirect('/settings')});
app.get('/logs',auth,async(req,res)=>{const entries=await logs();res.send(html('Logs',`<section class="card"><h3>50 Audit Terakhir</h3><table><tr><th>Waktu</th><th>ID</th><th>Tipe</th><th>Status</th></tr>${entries.map(x=>`<tr><td>${h(x.created_at)}</td><td>${h(x.user_id)}</td><td>${h(x.kind)}</td><td>${h(x.status)}</td></tr>`).join('')}</table></section>`))});
await init();const port=Number(process.env.PORT||3000);app.listen(port,'0.0.0.0',()=>console.log('Audit server ready on '+port));runBot().catch(e=>console.error('Bot stopped:',e.message));
